#include <iostream>
//this code generated by Altay Kırlı 2020 in 25.11.2020 at 05:32
using namespace std;

class Kisi {
public:
  string adi;
  string soyadi;
  float maas= 2558.4;
  int tc;
};


class Konut {
	public:
		string adres;
		int birimfiyat;
		int metrekare;

float hesap(){
		
	return(birimfiyat * metrekare);
}
};

int main() {
  Kisi k1, k2;
  Konut e1, e2;
  
  
  k1.adi = "Ali";
  k1.soyadi = "Ak";
  k1.tc = 54511412554;
  k1.maas;
   
  k2.adi = "Mehmet Ali";
  k2.soyadi = "Ceran";
  k2.maas = 5000;
  k2.tc = 11111212121;
  
  
   
  e1.adres = "Elmasehir mahallesi 11.Blok 2.kat";
  e1.birimfiyat = 1000;
  e1.metrekare = 145;
  
  cout << "1. ev adresi: " << e1.adres << endl 
  		 << "Birim fiyati: " << e1.birimfiyat << endl 
		   	<< "Metrekare: " << e1.metrekare << endl
  				 << "1. ev satis fiyati: " <<  e1.hesap() << endl << endl; 
	
  cout << "2. ev adres Gir: " << endl;
  cin >> e2.adres;
  cout << endl;
  
  
  cout << "2. ev birimfiyat Gir: " << endl;
  cin >> e2.birimfiyat;
  cout << endl;

  
  cout << "2. ev metrekare Gir: " << endl;
  cin >> e2.metrekare;
  cout << endl;

  

  cout << "Adres: " << e2.adres << endl
  		<< "Birim fiyat: " << e2.birimfiyat << endl
		  << "Metrekare: " << e2.metrekare << endl;
		  
		  
  cout << "Satis fiyati: " <<  e2.hesap() << endl; 

  return 0;
}
